server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: ProductLoadBalancer
          uri: lb://ProductLoadBalancer
          predicates:
            - Path=/product/**
        - id: CustomerService
          uri: lb://CustomerService
          predicates:
            - Path=/customer/**
        - id: CustomerService
          uri: lb://CustomerService
          predicates:
            - Path=/customer/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/order/**
        - id: ShoppingCartService
          uri: lb://ShoppingCartService
          predicates:
            - Path=/shoppingcart/**
        - id: CartServiceViewer
          uri: lb://CartServiceViewer
          predicates:
            - Path=/shoppingcartviewer/**
          filters:
            - name: CircuitBreaker
              args:
                name: ProductLoadBalancer
                fallbackUri: forward:/product-fallback
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms


  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  resilience4j:
    circuitbreaker:
      instances:
        PRODUCT-SERVICE:
          slidingWindowSize: 10
          permittedNumberOfCallsInHalfOpenState: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 10000
          registerHealthIndicator: true
    timelimiter:
      instances:
        PRODUCT-SERVICE:
          timeoutDuration: 2s
