server:
  port: 0
spring:
  data:
    mongodb:
      database: WebStoreDB
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/, http://localhost:8089/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
