spring:
  data:
    mongodb:
      database: WebStoreDB
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
