spring:
  application:
    name: ProductService
  config:
    import: optional:configserver:http://localhost:8888/
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #100% (default 10%)

