server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/products/**