server:
  port: 8092

spring:
  application:
    name: Shopping Cart Service

#Monogo Database
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: ShoppingCartDB

  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

